version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: proxy_nginx
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/certs/dhparams.pem:/etc/nginx/certs/dhparams.pem
      - ./nginx/certs/pluralcamp.com/cert.pem:/etc/nginx/certs/pluralcamp.com/fullchain.cer
      - ./nginx/certs/pluralcamp.com/key.pem:/etc/nginx/certs/pluralcamp.com/pluralcamp.com.key
        #- ./nginx/certs/pluralcamp.com/fullchain.pem:/etc/nginx/certs/pluralcamp.com/fullchain.cer
        #- ./nginx/certs/pluralcamp.com/privkey.pem:/etc/nginx/certs/pluralcamp.com/pluralcamp.com.key
    ports:
      - 443:443
    network_mode: "host"
    restart: unless-stopped
